// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: proto/calculator.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculationStatus int32

const (
	CalculationStatus_OK     CalculationStatus = 0
	CalculationStatus_FAILED CalculationStatus = 1
)

// Enum value maps for CalculationStatus.
var (
	CalculationStatus_name = map[int32]string{
		0: "OK",
		1: "FAILED",
	}
	CalculationStatus_value = map[string]int32{
		"OK":     0,
		"FAILED": 1,
	}
)

func (x CalculationStatus) Enum() *CalculationStatus {
	p := new(CalculationStatus)
	*p = x
	return p
}

func (x CalculationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CalculationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_calculator_proto_enumTypes[0].Descriptor()
}

func (CalculationStatus) Type() protoreflect.EnumType {
	return &file_proto_calculator_proto_enumTypes[0]
}

func (x CalculationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CalculationStatus.Descriptor instead.
func (CalculationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{0}
}

type Operation int32

const (
	Operation_MUL Operation = 0
	Operation_DIV Operation = 1
	Operation_SUB Operation = 2
	Operation_SUM Operation = 3
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "MUL",
		1: "DIV",
		2: "SUB",
		3: "SUM",
	}
	Operation_value = map[string]int32{
		"MUL": 0,
		"DIV": 1,
		"SUB": 2,
		"SUM": 3,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_calculator_proto_enumTypes[1].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_proto_calculator_proto_enumTypes[1]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{1}
}

type CalculateMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation string  `protobuf:"bytes,1,opt,name=Operation,proto3" json:"Operation,omitempty"`
	Operand1  float64 `protobuf:"fixed64,2,opt,name=Operand1,proto3" json:"Operand1,omitempty"`
	Operand2  float64 `protobuf:"fixed64,3,opt,name=Operand2,proto3" json:"Operand2,omitempty"`
}

func (x *CalculateMessage) Reset() {
	*x = CalculateMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateMessage) ProtoMessage() {}

func (x *CalculateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateMessage.ProtoReflect.Descriptor instead.
func (*CalculateMessage) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateMessage) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *CalculateMessage) GetOperand1() float64 {
	if x != nil {
		return x.Operand1
	}
	return 0
}

func (x *CalculateMessage) GetOperand2() float64 {
	if x != nil {
		return x.Operand2
	}
	return 0
}

type CalculatedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result            float64              `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	CalculationDate   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=calculationDate,proto3" json:"calculationDate,omitempty"`
	CalculationTime   float64              `protobuf:"fixed64,3,opt,name=calculationTime,proto3" json:"calculationTime,omitempty"`
	CalculationStatus string               `protobuf:"bytes,4,opt,name=calculationStatus,proto3" json:"calculationStatus,omitempty"`
}

func (x *CalculatedMessage) Reset() {
	*x = CalculatedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatedMessage) ProtoMessage() {}

func (x *CalculatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatedMessage.ProtoReflect.Descriptor instead.
func (*CalculatedMessage) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *CalculatedMessage) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *CalculatedMessage) GetCalculationDate() *timestamp.Timestamp {
	if x != nil {
		return x.CalculationDate
	}
	return nil
}

func (x *CalculatedMessage) GetCalculationTime() float64 {
	if x != nil {
		return x.CalculationTime
	}
	return 0
}

func (x *CalculatedMessage) GetCalculationStatus() string {
	if x != nil {
		return x.CalculationStatus
	}
	return ""
}

var File_proto_calculator_proto protoreflect.FileDescriptor

var file_proto_calculator_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x10, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x31, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x6e, 0x64, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x6e, 0x64, 0x32, 0x22, 0xc9, 0x01, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x44, 0x0a, 0x0f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x2c, 0x0a, 0x11, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a,
	0x27, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x2a, 0x2f, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x55, 0x4c, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x03, 0x44, 0x49, 0x56, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x55, 0x42, 0x10, 0x02,
	0x12, 0x07, 0x0a, 0x03, 0x53, 0x55, 0x4d, 0x10, 0x03, 0x32, 0x42, 0x0a, 0x0a, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x34, 0x0a, 0x09, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x12, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x42, 0x1c, 0x0a,
	0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x72, 0x72, 0x70, 0x2e, 0x74, 0x72, 0x72, 0x70, 0x33, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x01, 0x5a, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_calculator_proto_rawDescOnce sync.Once
	file_proto_calculator_proto_rawDescData = file_proto_calculator_proto_rawDesc
)

func file_proto_calculator_proto_rawDescGZIP() []byte {
	file_proto_calculator_proto_rawDescOnce.Do(func() {
		file_proto_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_calculator_proto_rawDescData)
	})
	return file_proto_calculator_proto_rawDescData
}

var file_proto_calculator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_calculator_proto_goTypes = []interface{}{
	(CalculationStatus)(0),      // 0: CalculationStatus
	(Operation)(0),              // 1: Operation
	(*CalculateMessage)(nil),    // 2: CalculateMessage
	(*CalculatedMessage)(nil),   // 3: CalculatedMessage
	(*timestamp.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_calculator_proto_depIdxs = []int32{
	4, // 0: CalculatedMessage.calculationDate:type_name -> google.protobuf.Timestamp
	2, // 1: Calculator.Calculate:input_type -> CalculateMessage
	3, // 2: Calculator.Calculate:output_type -> CalculatedMessage
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_calculator_proto_init() }
func file_proto_calculator_proto_init() {
	if File_proto_calculator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_calculator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculatedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_calculator_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calculator_proto_goTypes,
		DependencyIndexes: file_proto_calculator_proto_depIdxs,
		EnumInfos:         file_proto_calculator_proto_enumTypes,
		MessageInfos:      file_proto_calculator_proto_msgTypes,
	}.Build()
	File_proto_calculator_proto = out.File
	file_proto_calculator_proto_rawDesc = nil
	file_proto_calculator_proto_goTypes = nil
	file_proto_calculator_proto_depIdxs = nil
}
